name: "My Composit Action"
description: "A reusable composit action that checks out code and sets up Node.js"

inputs: 
  node-version: 
    description: "The Node.js version to use"
    required: true

runs:
  using: "composite"
  steps:

    - id: run-script 
      run: echo "results= Success" >> $GITHUB_OUTPUT
      shell: bash