name: build with composite action
on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use My composite action to build 
        uses: ./.github/actions/my-composite-action

