name: build with composite action
on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Use My composite action to build 
        uses: ./.github/actions/my-composite-action

