name: Composite action experiment 
on:
  pull-request:
    types: [open]
permissions: 
  pull-request: write 

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: Use my composite action
        uses: ./.github/actions/my-composite-action
        with: 
          node-version: '18'